config/routes.rb
Project532::Application.routes.draw do

  root to: "home#index"

  devise_for :users

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users
  end

  resources :categories, :departments, :products, :meals, :orders, :kids, :users

  get 'templates' => 'templates#index'

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  belongs_to :user
  has_many :meals, through: :orders
  has_many :orders

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render action: 'show', status: :created, location: @kid }
      else
        format.html { render action: 'new' }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params[:kid]
    end
end

app/views/kids/_form.html.haml
= semantic_form_for @kid do |f|
  = f.inputs
  = f.actions

app/views/kids/edit.html.haml
%h1 Editing kid

= render 'form'

= link_to 'Show', @kid
\|
= link_to 'Back', kids_path

app/views/kids/index.html.haml
%h1 Listing kids

%table
  %tr
    %th
    %th
    %th

  - @kids.each do |kid|
    %tr
      %td= link_to 'Show', kid
      %td= link_to 'Edit', edit_kid_path(kid)
      %td= link_to 'Destroy', kid, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Kid', new_kid_path

app/views/kids/new.html.haml
%h1 New kid

= render 'form'

= link_to 'Back', kids_path

app/views/kids/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_kid_path(@kid)
\|
= link_to 'Back', kids_path