config/routes.rb
Project532::Application.routes.draw do

  root to: "home#index"

  devise_for :users

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users
  end

  resources :categories, :departments, :products, :meals, :orders, :kids, :users

  get 'templates' => 'templates#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.hero.well
  %h1 Sandbox System
  Nothing else just sandboxing
.well
  .row
    .span3
      %h3 Mockups:
    .span3
      =link_to "Check a static admin template", templates_path, class: "btn btn-large btn-warning"
    .span3
      =link_to "A static product page view", products_path, class: "btn btn-large btn-success"
  .row
    .span3
      %h3 Dynamic staffs:
    .span3
      =link_to "Category management with nested model", categories_path, class: 'btn btn-large btn-danger'
    .span3
      =link_to "Dynamic page for Departments model", departments_path, class: 'btn btn-large btn-info'
  .row
    .span3
      %h3 Polymorphic models and forms
    .span3
      =link_to "Manage meals model", meals_path, class: 'btn btn-large btn-warning'
      =link_to "Manage kids model", kids_path, class: 'btn btn-large'
      =link_to "Manage users model", users_path, class: 'btn btn-large'
    .span3
      =link_to "Manage orders with nested form", orders_path, class: 'btn btn-large btn-success'
  .row
    .span3
      %h3 Latest task
    .span3
      =link_to 'User model', users_path, class: 'btn btn-large btn-success'
    .span
      %ul
        %li User create with a polymorphic model
        %li Meal list is fixed in seed
        %li Join table has an extra field: vegetarian (Join table: order)
  .row
    %h3 New todo list
    %ul
      %li Create a product database
      %li Create printer_type and printer_join tables
      %li Join together these models
      %li Create a form with nested attributes