config/routes.rb
Project532::Application.routes.draw do

  root to: "home#index"

  devise_for :users

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users
  end

  resources :categories, :departments, :products, :meals, :orders, :kids, :users

  get 'templates' => 'templates#index'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :kids, through: :orders
  has_many :users, through: :orders
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meal }
      else
        format.html { render action: 'new' }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params[:meal].permit(:name, :price)
    end
end

app/views/meals/_form.html.haml
= semantic_form_for @meal do |f|
  = f.inputs
  = f.actions

app/views/meals/edit.html.haml
%h1 Editing meal

= render 'form'

= link_to 'Show', @meal
\|
= link_to 'Back', meals_path

app/views/meals/index.html.haml
%h1 Listing meals

.well
  = link_to 'New Meal', new_meal_path, class: 'btn btn-success btn-large'

%table.table.table-striped
  %tr
    %th Name
    %th Price
    %th
    %th
    %th

  - @meals.each do |meal|
    %tr
      %td= meal.name
      %td= meal.price
      %td= link_to 'Show', meal, class: 'btn'
      %td= link_to 'Edit', edit_meal_path(meal), class: 'btn'
      %td= link_to 'Destroy', meal, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/meals/new.html.haml
%h1 New meal

= render 'form'

= link_to 'Back', meals_path

app/views/meals/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_meal_path(@meal)
\|
= link_to 'Back', meals_path