config/routes.rb
Project532::Application.routes.draw do

  root to: "home#index"

  devise_for :users

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users
  end

  resources :categories, :departments, :products, :meals, :orders, :kids, :users

  get 'templates' => 'templates#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set

  belongs_to  :department

  #this can be null and is only for hierarchy
  has_many    :sub_categories,    class_name: 'Category'
  belongs_to  :category,   class_name: 'Category', foreign_key: 'parent_id'

  has_many    :products

  has_attached_file :attachment, style: {medium: '500x500>', thumb: '50x50>'}

  validates   :name, presence: true, uniqueness: true

  def to_jq_upload
    {
      "name" => read_attribute(:attachment_file_name),
      "size" => read_attribute(:attachment_file_size),
      "url" => attachment.url(:original),
      "delete_url" => attachment_path(self),
      "delete_type" => "DELETE"
    }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :set_category, only: [:show, :edit, :update, :destroy]
    add_crumb('Categories') {|instance| instance.send :categories_path }

    respond_to :js, :html

    def index
      @categories = Category.all.order(lft: :asc)
    end

    def show
    end

    def new
      @category = Category.new
    end


    def edit
    end

    def create
      @category = Category.new(category_params)

      @category.save
      @categories = Category.all #Need for 'parent_category_list' in Helper to generate a dropdown list.
      respond_to do |f|
        f.html { redirect_to(categories_path)}
        f.js
      end
    end

    def update
      respond_to do |format|
        if @category.update(category_params)
          format.json {head :ok}
        else
          format.json {render json: @category.errors.full_messages, status: :unprocessable_entity}
        end
      end
    end

    def destroy
      @category.destroy
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end


    def category_params
      params[:category].permit(:name, :parent_id, :attachment)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def parent_category_list
    result = [[nil, '-']]
    @categories.each do |category|
      key = category.id
      value = category.name
      result << [key, value]
    end
    result
  end

end

app/views/categories/_category.html.haml
%tr{id: "category_#{category.id}"}
  %td=best_in_place category, :parent_id, type: :select, collection: parent_category_list
  %td=best_in_place category, :name, type: :input, ok_button: "OK", ok_button_class: 'btn', :activator => "#activator-#{category.id}"
  %td=image_tag category.attachment(:thumb)
  %td=link_to 'Edit', edit_category_path(category), id: "activator-#{category.id}", class: 'btn', remote: true
  %td=link_to 'Delete', category, method: :delete, class: 'btn', remote: true, data: {confirm: 'Are you sure?'}

app/views/categories/_form.html.haml
#formModal.modal.hide.fade{role: 'dialog', 'aria-labelledby' => 'New Business', 'aria-hidden' => 'false'}
  .modal-header
    %a.close{type: 'button', data:{dismiss: 'modal'}, 'aria-hidden' => 'true'} &times;
    %h3#createModalLabel Create a New Category
  =semantic_form_for Category.new, remote: true, html: {multipart: true, id: 'fileupload'} do |f|
    .modal-body
      =f.input :parent, label: 'Parent Category'
      =f.input :name, label: 'Name:', require: true
      .row.fileupload-buttonbar
        .span5
          %span.btn.btn-success.fileinput-button
            %i.icon-plus.icon-white
            %span Add files...
            =f.file_field :attachment
          %button{type: 'submit', class:'btn btn-primary start'}
            %i.icon-upload.icon-white
            %span Start upload
          %button{type: 'reset', class:'btn btn-warning cancel'}
            %i.icon-ban-circle.icon-white
            %span Cancel upload
          %button{type: 'button', class:'btn btn-danger delete'}
            %i.icon-trash.icon-white
            %span Delete
          %input{type:'checkbox', class:'toggle'}
        .span5
          .progress.progress-success.progress-striped.active.fade
            .bar{style: 'width:0%;'}
      .fileupload-loading
      %br
      %table.table.table-striped
        %tbody.files{data:{toggle:'modal-gallery', target:'#modal-gallery'}}


      #error-message
    .modal-footer
      %a.btn.btn-large.btn-danger{data: {dismiss: 'modal'}, 'aria-hidden' => 'true'} Close
      =f.action :submit, :button_html => {class:'btn btn-primary btn-large'}
:plain
  <script>
    var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
    };
  </script>

  <!-- The template to display files available for upload -->
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
      <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
      <td>
        <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
      </td>
      <td class="start">{% if (!o.options.autoUpload) { %}
        <button class="btn btn-primary">
          <i class="icon-upload icon-white"></i>
          <span>{%=locale.fileupload.start%}</span>
        </button>
        {% } %}</td>
      {% } else { %}
      <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="btn btn-warning">
          <i class="icon-ban-circle icon-white"></i>
          <span>{%=locale.fileupload.cancel%}</span>
        </button>
        {% } %}</td>
    </tr>
    {% } %}
  </script>
  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-download fade">
        {% if (file.error) { %}
          <td></td>
          <td class="name"><span>{%=file.name%}</span></td>
          <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
          <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
          {% } else { %}
          <td class="preview">{% if (file.thumbnail_url) { %}
            <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
          <td class="name">
            <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
          </td>
          <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
          <td colspan="2"></td>
          {% } %}
        <td class="delete">
          <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
            <i class="icon-trash icon-white"></i>
            <span>{%=locale.fileupload.destroy%}</span>
          </button>
          <input type="checkbox" name="delete" value="1">
        </td>
      </tr>
      {% } %}
  </script>

  <script type="text/javascript" charset="utf-8">
    $(function () {
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload();
        //
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          var fu = $('#fileupload').data('blueimpFileupload'),
            template;
          fu._adjustMaxNumberOfFiles(-files.length);
          console.log(files);
          template = fu._renderDownload(files)
            .appendTo($('#fileupload .files'));
          // Force reflow:
          fu._reflow = fu._transition && template.length &&
            template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
        });

    });
  </script>

app/views/categories/index.html.haml
.container
  %h1 Category management
  .well{style: 'height: 50px'}
    .pull-left Manage your category list or create a new one.
    %a.pull-right.btn.btn-success.btn-large{data: {toggle: 'modal'}, href: '#formModal'} New Category
  %table.table.table-bordered#categories
    %tr
      %th Parent Category (click on it to change)
      %th Name
      %th Image
      %th Edit
      %th Delete
    =render @categories
  =render 'form'